models:
  - name: customers_stg
    description: Staged customer data from order management system (OMS), with minor row-level transformations.  
    columns:
      - name: Email
        description: Customer's Primay Email address for promotions and offers.      
        tests:
          - string_not_empty


  - name: orders_stg
    description: Staged orders data from order management system (oms), with minor row-level transformations.  
    columns:
      - name: ORDERID
        description: The primary key for orders_stg table.      
        tests:
          - unique
          - not_null

      - name: STATUSCD
        description: "{{ doc('StatusCD') }}"    
        tests:
          - accepted_values:
              arguments:
                values: ['01', '02', '03']

  - name: orderitems_stg
    description: Staged order items data from order management system (oms), with minor row-level transformations.   
    columns:
      - name: ORDERID
        tests:
          - relationships:
              arguments:
                to: ref('orders_stg')
                field: ORDERID
  - name: orderitems_uniq
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          arguments:
            compare_model: ref("orders_stg")